export const ADD_NEW_PERSON = 'ADD_NEW_PERSON'
export const FETCH_PERSONS = 'FETCH_PERSONS'
export const CHANGE_ACTIVE_PERSON = 'CHANGE_ACTIVE_PERSON'
export const DELETE_PERSON = 'DELETE_PERSON'
export const EDIT_PERSON = 'EDIT_PERSON'
export const SET_PERSON_BY_ID = 'SET_PERSON_BY_ID'
export const CHANGE_EDIT_MODE = 'CHANGE_EDIT_MODE'

export const FETCH_POSTS = 'FETCH_POSTS'
export const CHANGE_ADD_POST = 'CHANGE_ADD_POST'
export const ADD_POST = 'ADD_POST'

export const ADD_NEW_ALBUM = "ADD_NEW_ALBUM"
export const FETCH_ALBUMS = "FETCH_ALBUMS"
export const CHANGE_ADD_ALBUM_MODE = "CHANGE_ADD_ALBUM_MODE"
export const SET_ALBUM_BY_ID = "SET_ALBUM_BY_ID"

export const ADD_PHOTO = "ADD_PHOTO"
export const FETCH_PHOTOS = "FETCH_PHOTOS"